[platformio]
default_envs = pico2_master

[env:pico2_master]
platform = raspberrypi
board = rpipico2
framework = arduino
monitor_port = COM19
monitor_speed = 115200
extra_scripts = pre:scripts/patch_tinyusb_cdc.py
build_src_filter = +<pico_master.cpp>
lib_deps = 
    greiman/SdFat@^2.2.3
    mikalhart/TinyGPSPlus@^1.0.3
    adafruit/Adafruit NeoPixel@^1.12.0
    urban-machine/xxHash@0.8.1-pio.1
build_flags =
    -DUSE_TINYUSB
    -DCFG_TUSB_CONFIG_FILE=\"custom_tusb_config.h\"
    -Iinclude
    -DLOG_DEDUPE_HITS=1
    -DWIFI_DEDUPE_HASH_BITS=64

[env:esp32c5_slave]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c5-devkitc1-n8r4
framework = arduino
upload_port = COM18
monitor_speed = 115200
monitor_port = COM18
build_src_filter = +<esp32_slave.cpp>
lib_deps =
    urban-machine/xxHash@0.8.1-pio.1
build_flags = 
    -DPIN_SCK=6
    -DPIN_MOSI=1
    -DPIN_MISO=0
    -DPIN_CS=24
    -DLOG_DEDUPE_HITS=1
    -DWIFI_DEDUPE_HASH_BITS=64
